api/urls.py
from django.urls import path
from . import views

app_name = 'api'
urlpatterns = [
  path('students/', views.list_students,),
  path('students/<str:pk>', views.list_student),
]

first_app/urls.py
from django.urls import path
from . import views

app_name = 'first_app'
urlpatterns = [
  path('', views.index, name='index'),
  path('variable/', views.variable_view, name='variable'),
  path('list/', views.list_students, name='list'),
  path('add/', views.add_student, name='add'),
  path('delete/', views.delete_student, name='delete'),
  path('update/', views.update_student, name='update'),
  path('update/<int:id>/', views.update_student, name='update'),
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls'))
]

api/models.py
from django.db import models

# Create your models here.
class StudentApi(models.Model):
  name = models.CharField(max_length=60)
  roll_no = models.CharField(max_length=60)


  def __str__(self):
    return self.name

first_app/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
  name = models.CharField(max_length=30)
  age = models.IntegerField()
  branch = models.CharField(max_length=30)
  roll_no = models.IntegerField()

  def __str__(self):
    return f"The student details are: {self.name}, {self.age}, {self.branch}, {self.roll_no}"

api/views.py
from django.shortcuts import render
from itsdangerous import Serializer
from rest_framework import viewsets
from .models import StudentApi
from .serializers import StudentApiSerializer
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from api import serializers

# Create your views here.
@api_view(['GET', 'POST'])
def list_students(request):
  if request.method == 'GET':
    students = StudentApi.objects.all()
    Serializer = StudentApiSerializer(students, many = True)
    return Response(Serializer.data)
  elif request.method == 'POST':
    print(request.data)
    serializer = StudentApiSerializer(data=request.data)
    if serializer.is_valid():
      serializer.save()
      return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'PUT', 'DELETE'])
def list_student(request, pk):
  if request.method == 'GET':
    student = StudentApi.objects.get(id=pk)
    serializer = StudentApiSerializer(student, many = False)
    return Response(serializer.data)
  elif request.method == 'PUT':
    student = StudentApi.objects.get(id=pk)
    serializer = StudentApiSerializer(student, data = request.data)
    if serializer.is_valid():
      serializer.save()
      return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
  elif request.method == 'DELETE':
    student = StudentApi.objects.get(id=pk)
    student.delete()
    return Response(status=status.HTTP_204_NO_CONTENT)

first_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from first_app.models import Student
# Create your views here.


def index(request):
  return render(request, 'first_app/example.html')


def variable_view(request):
  view_variable = {'first_name': 'Yaswanth', 'last_name': 'Bethu'}
  return render(request, 'first_app/variable.html', context=view_variable)

def list_students(request):
  all_students = Student.objects.all()
  context = {'students': all_students}
  return render(request, 'first_app/list.html', context=context)

def add_student(request):
  if request.POST:
    name = request.POST['name']
    age = int(request.POST['age'])
    branch = request.POST['branch']
    roll_no = int(request.POST['roll_no'])
    Student.objects.create(name=name, age=age, branch=branch, roll_no=roll_no)
    return redirect(reverse('first_app:list'))
  else:
    return render(request, 'first_app/add.html')

def delete_student(request):
  if request.POST:
    roll_no = request.POST['roll_no']
    try:
      Student.objects.get(roll_no=roll_no).delete()
      return redirect(reverse('first_app:list'))
    except :
      print(f'The student with roll number {roll_no} not found.')
      return redirect(reverse('first_app:list'))
  else:
    return render(request, 'first_app/delete.html')


def update_student(request, *args, **kwargs):
  all_students = Student.objects.all()
  context = {'students': all_students}
  print(args, kwargs)
  if len(kwargs) == 0:
    return render(request, 'first_app/update.html', context=context)
  elif request.POST:
    print(request.POST, kwargs)
    student = Student.objects.get(id=int(kwargs['id']))
    student.name = request.POST['name']
    student.age = int(request.POST['age'])
    student.branch = request.POST['branch']
    student.roll_no = int(request.POST['roll_no'])
    student.save()
    return redirect(reverse('first_app:list'))

  else:
    print("hello", kwargs)
    context = Student.objects.get(id=int(kwargs['id'])).__dict__
    print(context)
    return render(request, 'first_app/edit.html', context=context)

first_app/templates/first_app/add.html
{% extends "base.html"%}

{% block content%}
<div>
  <h1>add a new student to the database :</h1>
  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="">Name : </label>
      <input class="form-control" type="text" name="name" id="name" placeholder="ex: John Smith">
    </div>
    <div class="form-group">
      <label for="">Age : </label>
      <input class="form-control" type="number" name="age" id="age" placeholder="ex: 21">
    </div>
    <div class="form-group">
      <label for="">Branch : </label>
      <input class="form-control" type="text" name="branch" id="branch" placeholder="ex: CSE, ECE e.t.c">
    </div>
    <div class="form-group">
      <label for="">Roll Number : </label>
      <input class="form-control" type="number" name="roll_no" id="roll_no" placeholder="ex: 1,2,..">
    </div>
    <input class = "btn btn-primary" type="submit" value="Add">
  </form>
</div>

{% endblock %}

first_app/templates/first_app/delete.html
{% extends "base.html"%}

{% block content%}
<h1>Delete</h1>
<div>
  <h1>Enter roll number to delete the record :</h1>
  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="">Roll Number :  : </label>
      <input class="form-control" type="text" name="roll_no" id="roll_no" placeholder="ex: 1,2,3..">
    </div>
    <input class = "btn btn-primary" type="submit" value="Delete">
  </form>
</div>

{% endblock %}

first_app/templates/first_app/edit.html
{% extends "base.html"%}

{% block content%}
<div>
  <h1>Edit student details :</h1>
  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="">Name : </label>
      <input class="form-control" type="text" name="name" id="name" value= "{{name}}">
    </div>
    <div class="form-group">
      <label for="">Age : </label>
      <input class="form-control" type="number" name="age" id="age" value="{{age}}">
    </div>
    <div class="form-group">
      <label for="">Branch : </label>
      <input class="form-control" type="text" name="branch" id="branch" value="{{branch}}">
    </div>
    <div class="form-group">
      <label for="">Roll Number : </label>
      <input class="form-control" type="number" name="roll_no" id="roll_no" value="{{roll_no}}">
    </div>
    <input class = "btn btn-primary" type="submit" value="Update">
  </form>
</div>

{% endblock %}

first_app/templates/first_app/example.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Example html template connected!</h1>
  <h1><a href="{% url 'first_app:variable' %}">Click Here</a></h1>
</body>
</html>

first_app/templates/first_app/list.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1>List of Students : </h1>
<ul>
{% for student in students%}
  <li>
  {{ student }}
  </li>
{% endfor %}
</ul>
</div>
{% endblock %}

first_app/templates/first_app/update.html
{% extends "base.html" %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  <div class="container">
    <h1>List of Students : </h1>
  <ul>
  {% for student in students%}
    <li>
    {{ student }} <a href="{{student.id}}">Update</a>
    </li>
  {% endfor %}
  </ul>
  </div>
{% endblock %}

first_app/templates/first_app/variable.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Variable</title>
</head>
<body>
  <h1>variable.html</h1>
  <h1>{{first_name | lower | capfirst }}</h1>
  <h2>{# This is a comment #}</h2>
</body>
</html>

templates/base.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <title>Document</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'first_app:list'%}">List</a>
        <a class="nav-item nav-link" href="{% url 'first_app:add'%}">Add</a>
        <a class="nav-item nav-link" href="{% url 'first_app:delete'%}">Delete</a>
        <a class="nav-item nav-link" href="{% url 'first_app:update'%}">Update</a>

      </div>
    </div>
  </nav>
{% block content%}
{% endblock %}
</body>
</html>